spring:
  application:
    name: resident-manager

  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    driverClassName: "org.postgresql.Driver"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
  sql:
    init:
      platform: postgres

  # JPA settings (optional: auto-create tables from entities)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
