spring:
  application:
    name: resident-manager

  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true

# JPA settings (optional: auto-create tables from entities)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
